---
title: "Open source water quality reporting tools for the PEP Monitoring Collaborative"
author: "[Dr. Marcus Beck](mailto:mbeck@tbep.org) $\\bullet$ [\\@fawda123](https://twitter.com/fawda123)	$\\bullet$ [#TampaBayOpensci](https://twitter.com/hashtag/TampaBayOpenSci?src=hashtag_click)"
institute: "Tampa Bay Estuary Program"
date: "10/19/2020"
output:
  xaringan::moon_reader:
    nature:
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
    lib_dir: libs
    css: styles.css
    includes: 
      after_body: insert-logo-tbep.html
---

```{r, message = F, echo = F, warning = F}
library(knitr)
library(tbeptools)
library(tidyverse)
library(lubridate)
library(extrafont)
library(xaringanExtra)

use_panelset()

loadfonts(device = 'win', quiet = T)

fml <- 'Lato Light'

# global knitr options
opts_chunk$set(message = FALSE, dev.args = list(family = fml), dpi = 300, dev = 'png', echo = F, warning = F, fig.align = 'center', out.width = '100%')

```

class: center, top

# Agenda

---

class: center, top

# Open Science 101

What, why, how

---

class: center, top

# Application at TBEP

---

class: center, top

# Water quality assessment framework 

* Report card
* Methods (mag/duration)

---

class: center, top

# Application to PEP data (Suffolk County)

Make sure to link to CCMP actions in tech memo (only chl/secchi for now)
Main goals = fixed vs changing thresholds? which criteria? medians/means? 

---

class: center, top

# pepreporting package

---

class: center, top

# pepreporting package

Utility - functions, testing different thresholds, rapid acquisition/synthesis/reporting

---

class: center, top

# Contrast with prelim stoplight graphics in tech memo, i.e., did not combine indicators, only basedon exceedence

---

class: center, top

# Potential products

---

class: center, top


---


